/**
 * Shared Codex CLI config constants.
 * Imported by both install-git-hooks.ts and core.ts.
 */

export const CODEX_CONFIG_TOML = `# Codex CLI configuration — generated by Harness Engineering and Orchestrator
# Notification hooks receive JSON on stdin and run asynchronously (non-blocking).

notify = ["bun .harness/runtime/hooks/check-guardian.ts --codex"]
`

export const CODEX_GUARDIAN_RULES = `# Codex CLI execpolicy rules — generated by Harness Engineering and Orchestrator
# Format: prefix_rule() entries evaluated by Codex execpolicy.
# NOTE: If Codex CLI updates its execpolicy syntax, these rules may need updating.
# As a fallback, the same rules are reinforced in AGENTS.md "Forbidden Operations"
# and enforced at commit time by git pre-commit hooks.
# Codex matches command prefixes, so git hooks remain the final guardrail when
# a flag appears later in the command than these rules can express.

# G2 / bypass prevention: block --no-verify flag
prefix_rule(
  pattern = ["git", "commit", "--no-verify"],
  decision = "forbidden",
  justification = "Do not bypass git hooks. Run git commit without --no-verify.",
  match = ["git commit --no-verify -m \\"T001: test\\""],
  not_match = ["git commit -m \\"T001: test\\""],
)
prefix_rule(
  pattern = ["git", "push", "--no-verify"],
  decision = "forbidden",
  justification = "Do not bypass git hooks. Run git push without --no-verify.",
  match = ["git push --no-verify origin main"],
  not_match = ["git push origin main"],
)

# G9: LEARNING.md must not be staged
prefix_rule(
  pattern = ["git", "add", "LEARNING.md"],
  decision = "forbidden",
  justification = "Do not stage LEARNING.md. Move the notes to the user-level knowledge base instead.",
  match = ["git add LEARNING.md"],
  not_match = ["git add README.md"],
)
prefix_rule(
  pattern = ["git", "add", "./LEARNING.md"],
  decision = "forbidden",
  justification = "Do not stage LEARNING.md. Move the notes to the user-level knowledge base instead.",
  match = ["git add ./LEARNING.md"],
  not_match = ["git add ./README.md"],
)

# Dangerous staging commands: block git add . and git add -A
prefix_rule(
  pattern = ["git", "add", "."],
  decision = "forbidden",
  justification = "Stage only the files you intend to change instead of using git add .",
  match = ["git add ."],
  not_match = ["git add src/index.ts"],
)
prefix_rule(
  pattern = ["git", "add", "-A"],
  decision = "forbidden",
  justification = "Stage only the files you intend to change instead of using git add -A.",
  match = ["git add -A"],
  not_match = ["git add -p"],
)
`
